In [1]:
import pandas as pd

In [2]:
# load the csv
df = pd.read_csv('df.csv')

df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,Category,Loved,Hated
0,df4c4464-e2cc-48d8-8cc4-f5ff5b7ec649,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"worst app ever, i get debited every time Even ...",1,0,1.36.2,2025-09-05 05:10:29,"Hello Comfort,\nWe’re sorry for the frustratio...",2025-09-05 14:41:33,1.36.2,Transaction Charges,NaN,transaction charges
1,10fd9fcf-2042-4c6e-80d8-80b0632c6489,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,I love it,5,0,NaN,2025-09-05 04:26:12,"Hello Ifeoluwa, We're overjoyed to hear that M...",2025-09-05 14:33:59,NaN,General Feedback,NaN,NaN
2,0feefd4c-fa95-460a-b474-f76838eeec87,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,very awaresome,5,0,1.38.0,2025-09-05 04:16:55,"Hello Saleh, We're overjoyed to hear that Moni...",2025-09-05 14:33:31,1.38.0,General Feedback,NaN,NaN
3,0455d65c-1d1a-427c-8c74-2f0fcc4629fd,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Good,5,0,1.32.1,2025-09-05 04:04:08,"Hello Ejide, Thank you so much for your encour...",2025-09-05 14:32:13,1.32.1,General Feedback,NaN,NaN
4,144f004f-bb52-4da8-98a4-fd40e10b106b,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,is nice and okay for ma lol,4,0,1.37.0,2025-09-05 03:27:03,"Hello Ojeleke, Thank you for taking time to ra...",2025-09-05 14:32:56,1.37.0,General Feedback,NaN,NaN

In [3]:
df.columns

Index(['reviewId', 'userName', 'userImage', 'content', 'score',
       'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent',
       'repliedAt', 'appVersion', 'Category', 'Loved', 'Hated'],
      dtype='object')

In [4]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd

analyzer = SentimentIntensityAnalyzer()

def get_fintech_sentiment(text):
    if pd.isna(text):
        return 'neutral', 0.0
    
    scores = analyzer.polarity_scores(str(text))
    compound = scores['compound']
    
    # Adjusted thresholds for app reviews (more sensitive)
    if compound >= 0.1:
        label = 'positive'
    elif compound <= -0.1:
        label = 'negative'
    else:
        label = 'neutral'
    
    return label, compound

# Apply to your dataframe
df[['sentiment_label', 'sentiment_score']] = df['content'].apply(
    lambda x: pd.Series(get_fintech_sentiment(x))
)

In [5]:
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,Category,Loved,Hated,sentiment_label,sentiment_score
0,df4c4464-e2cc-48d8-8cc4-f5ff5b7ec649,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"worst app ever, i get debited every time Even ...",1,0,1.36.2,2025-09-05 05:10:29,"Hello Comfort,\nWe’re sorry for the frustratio...",2025-09-05 14:41:33,1.36.2,Transaction Charges,NaN,transaction charges,negative,-0.5365
1,10fd9fcf-2042-4c6e-80d8-80b0632c6489,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,I love it,5,0,NaN,2025-09-05 04:26:12,"Hello Ifeoluwa, We're overjoyed to hear that M...",2025-09-05 14:33:59,NaN,General Feedback,NaN,NaN,positive,0.6369
2,0feefd4c-fa95-460a-b474-f76838eeec87,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,very awaresome,5,0,1.38.0,2025-09-05 04:16:55,"Hello Saleh, We're overjoyed to hear that Moni...",2025-09-05 14:33:31,1.38.0,General Feedback,NaN,NaN,neutral,0.0000
3,0455d65c-1d1a-427c-8c74-2f0fcc4629fd,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Good,5,0,1.32.1,2025-09-05 04:04:08,"Hello Ejide, Thank you so much for your encour...",2025-09-05 14:32:13,1.32.1,General Feedback,NaN,NaN,positive,0.4404
4,144f004f-bb52-4da8-98a4-fd40e10b106b,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,is nice and okay for ma lol,4,0,1.37.0,2025-09-05 03:27:03,"Hello Ojeleke, Thank you for taking time to ra...",2025-09-05 14:32:56,1.37.0,General Feedback,NaN,NaN,positive,0.7579

In [6]:
df.columns

Index(['reviewId', 'userName', 'userImage', 'content', 'score',
       'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent',
       'repliedAt', 'appVersion', 'Category', 'Loved', 'Hated',
       'sentiment_label', 'sentiment_score'],
      dtype='object')

In [7]:
# Save the final DataFrame to CSV
df.to_csv('df.csv', index=False)